### PR TITLE
fixed total count error

### LINKED ISSUE #25: Wrong question count
Start command gives question count more than actual questions exist.

```
$ php certificationy.php start --number 1000
Starting a new set of 252 questions (available questions: 425)
$ grep "\-$" vendor/certificationy/*/data/* | wc -l
252
```

### PR DESCRIPTION
**Pull request by mazhuravlev**
resolve #25

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hi,

Ok, make sense with previous pull request on ``certificationy`` library: I'll review it asap.

Thank you

**Comment by mazhuravlev** [comment]
This won't be needed if you accept [this lighter solution](https://github.com/certificationy/certificationy/pull/72)

**Comment by mickaelandrieu** [comment]
@mazhuravlev this need a rebase, sorry :)

**Comment by mickaelandrieu** [comment]
ping @mazhuravlev any news on this contribution ?

**Pull request closed without merging**
