### PR TITLE
Training mode: the solution is displayed after each question

### PR DESCRIPTION
**Pull request by jean-pasqualini**
Training mode: the solution is displayed after each question

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hi,

thank you for this contribution. Can you put a screenshot of the expected result ?

Also, I have relaunched the tests because the build is broken in php 5.6 (and clearly, I don't understand why).

Mickaël

**Comment by jean-pasqualini** [comment]
capture-certification

**Comment by mickaelandrieu** [comment]
Ok to me: I will write test :) 

Thanks

**Comment by mickaelandrieu** [comment]
Released ;)

**Pull request merged**
