### PR TITLE
Move certificationy console command to bin directory

### PR DESCRIPTION
**Pull request by spolischook**

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
I don't see the real value of this, what is your need ?

**Comment by spolischook** [comment]
First of all, It is something like convention in Symfony console applications, see:
https://github.com/doctrine/doctrine2/tree/master/bin
https://github.com/symfony/symfony-standard/tree/master/bin

But the most major issue is when i try run this command from vendor directory:
```bash
php vendor/certificationy/certificationy-cli/certificationy.php start
```
I get this error:
```
PHP Warning:  require(/home/spolischook/www/geekhub-php/exam/vendor/certificationy/certificationy-cli/vendor/autoload.php): failed to open stream: No such file or directory in /home/spolischook/www/geekhub-php/exam/vendor/certificationy/certificationy-cli/certificationy.php on line 14
PHP Stack trace:
PHP   1. {main}() /home/spolischook/www/geekhub-php/exam/vendor/certificationy/certificationy-cli/certificationy.php:0
PHP Fatal error:  require(): Failed opening required '/home/spolischook/www/geekhub-php/exam/vendor/certificationy/certificationy-cli/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/spolischook/www/geekhub-php/exam/vendor/certificationy/certificationy-cli/certificationy.php on line 14
PHP Stack trace:
PHP   1. {main}() /home/spolischook/www/geekhub-php/exam/vendor/certificationy/certificationy-cli/certificationy.php:0
```

**Comment by mickaelandrieu** [comment]
Hum ... I don't think it's a good idea to use certificationy-cli as a dependency, you should rely on certificationy library :)

More, I don't see why this fix your issue: I guess you are trying to do a web application right ?

Mickaël

**Comment by spolischook** [comment]
>  I guess you are trying to do a web application right ?

Did you have one?
This can be used if you have private repository with your own secret q/a and cli as dependency for it. For web applications as well.
We need some tested tool for our students, so we prefer keep our q/a in secret.

**Comment by spolischook** [comment]
However this is a bc break, so I can add bin application as synonym for current cli app.
See https://github.com/doctrine/doctrine2/blob/master/bin/doctrine

**Comment by mickaelandrieu** [comment]
Feel free to re-open if

**Pull request closed without merging**
